### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by macedogm** [openvex/vexctl#244]
Would it be possible, please, to cut a new tag release?
A lot of nice improvements were merged to main since v0.2.6 was released in Dec 2023 - https://github.com/openvex/vexctl/compare/v0.2.6...main.
Thanks!

**Comment by cpanato** [comment]
sounds good i can do that

**Comment by macedogm** [comment]
@cpanato thanks!

**Comment by cpanato** [comment]
out https://github.com/openvex/vexctl/releases/tag/v0.3.0

**Comment by macedogm** [comment]
Thanks a lot @cpanato 🙇🏻
