### ISSUE TITLE
Expose impact_statement in command line arguments

### ISSUE THREAD

**Issue by nishakm** [openvex/vexctl#66]
See Issue https://github.com/openvex/spec/issues/24 for context

The OpenVEX spec has the option to add `impact_statement` but this is not exposed in `vexctl create`. I currently have to add it outside of `vexctl`. The model has it though.

**Comment by puerco** [comment]
Thanks for filing the issue Nisha :) I've opened #74 to add a new flag to fix this one.

**Comment by nishakm** [comment]
Thanks @puerco!
