### ISSUE TITLE
Filtering of GHSA IDs?

### ISSUE THREAD

**Issue by johanngyger** [openvex/vexctl#78]
Currently, it's only possible to filter CVE IDs with `vexctl filter`. Are there any plans to support GHSA, too?

We ran into this issue with the latest kics image, and need to filter a GHSA ID `GHSA-gq5r-cc4w-g8xf`.

Here's the example:

```
trivy image --format sarif checkmarx/kics:v1.7.1-alpine
```

**Comment by puerco** [comment]
Thanks for reporting this Johann! Here you go :)
https://github.com/openvex/vexctl/pull/80
