### ISSUE TITLE
Support for PRISMA vulnerability identifiers

### ISSUE THREAD

**Issue by ferozsalam** [openvex/vexctl#86]
👋 hello! I was wondering if there would be interest in adding support for the `PRISMA-` style identifiers used by Palo Alto's Prisma Cloud. I'm currently getting errors when attempting to `vexctl filter` a SARIF report generated by Prisma Cloud.

From what I understand this should be a relatively simple change, I'm happy to open a PR for it if there's no objection.

**Comment by puerco** [comment]
Hey @ferozsalam not a problem I'd be super happy if you send us a PR, if not a sample of the SARIF document would be super helpful to make sure we support it.
