### ISSUE TITLE
Provide compiled binaries for each tagged release

### ISSUE THREAD

**Issue by chipzoller** [openvex/vexctl#89]
Compiled Go binaries should be made available for at least a minimal set of platforms for each tagged release obviating the need for `go install`.

**Comment by cpanato** [comment]
we have that https://github.com/openvex/vexctl/blob/main/.github/workflows/release.yaml we need a new release :)


@puerco can we plan a new release?

**Comment by chipzoller** [comment]
Binaries are available now starting in 0.2.3.
